import { CurrentCashBookResponseDto } from './current-cash-book.response.dto';

export const CurrentCashBookResponseDtoStub: CurrentCashBookResponseDto = {
  reportingMonths: [11, 10, 9, 8, 7, 6, 5, 4, 3, 2],
  membersWithMembershipFees: [
    {
      lastName: 'Берчук',
      firstName: 'Володимир',
      membershipFees: [
        { reportingMonth: 10, amount: 200 },
        { reportingMonth: 9, amount: 200 },
        { reportingMonth: 8, amount: 200 },
        { reportingMonth: 7, amount: 200 },
        { reportingMonth: 6, amount: 200 },
        { reportingMonth: 5, amount: 200 },
        { reportingMonth: 4, amount: 200 },
        { reportingMonth: 3, amount: 200 },
        { reportingMonth: 2, amount: 200 },
      ],
    },
    {
      firstName: 'Юлія',
      lastName: 'Білас',
      membershipFees: [
        { reportingMonth: 10, amount: 200 },
        { reportingMonth: 9, amount: 200 },
        { reportingMonth: 8, amount: 200 },
        { reportingMonth: 7, amount: 200 },
        { reportingMonth: 6, amount: 200 },
        { reportingMonth: 5, amount: 200 },
        { reportingMonth: 4, amount: 200 },
        { reportingMonth: 3, amount: 200 },
        { reportingMonth: 2, amount: 200 },
      ],
    },
    {
      lastName: 'Гамбарова',
      firstName: 'Еляна',
      membershipFees: [
        { reportingMonth: 10, amount: 200 },
        { reportingMonth: 9, amount: 200 },
        { reportingMonth: 8, amount: 200 },
        { reportingMonth: 7, amount: 200 },
        { reportingMonth: 2, amount: 200 },
      ],
    },
    {
      lastName: 'Дробчак',
      firstName: 'Ольга',
      membershipFees: [
        { reportingMonth: 9, amount: 200 },
        { reportingMonth: 7, amount: 200 },
        { reportingMonth: 6, amount: 200 },
        { reportingMonth: 5, amount: 200 },
        { reportingMonth: 4, amount: 200 },
        { reportingMonth: 3, amount: 200 },
        { reportingMonth: 2, amount: 200 },
      ],
    },
    {
      lastName: 'Коцюба',
      firstName: 'Галина',
      membershipFees: [
        { reportingMonth: 10, amount: 200 },
        { reportingMonth: 9, amount: 200 },
        { reportingMonth: 7, amount: 200 },
        { reportingMonth: 6, amount: 200 },
        { reportingMonth: 5, amount: 200 },
        { reportingMonth: 4, amount: 200 },
        { reportingMonth: 3, amount: 200 },
        { reportingMonth: 2, amount: 200 },
      ],
    },
    {
      lastName: 'Лех',
      firstName: 'Наталія',
      membershipFees: [
        { reportingMonth: 10, amount: 200 },
        { reportingMonth: 9, amount: 200 },
        { reportingMonth: 7, amount: 200 },
        { reportingMonth: 6, amount: 200 },
        { reportingMonth: 5, amount: 200 },
        { reportingMonth: 4, amount: 200 },
        { reportingMonth: 3, amount: 200 },
        { reportingMonth: 2, amount: 200 },
      ],
    },
    {
      lastName: 'Некрасова',
      firstName: 'Валентина',
      membershipFees: [
        { reportingMonth: 11, amount: 200 },
        { reportingMonth: 10, amount: 200 },
        { reportingMonth: 9, amount: 200 },
        { reportingMonth: 8, amount: 200 },
        { reportingMonth: 7, amount: 200 },
        { reportingMonth: 6, amount: 200 },
        { reportingMonth: 5, amount: 200 },
        { reportingMonth: 4, amount: 200 },
        { reportingMonth: 3, amount: 200 },
        { reportingMonth: 2, amount: 200 },
      ],
    },
    {
      lastName: 'Паращак',
      firstName: 'Надія',
      membershipFees: [
        { reportingMonth: 10, amount: 200 },
        { reportingMonth: 9, amount: 200 },
        { reportingMonth: 8, amount: 200 },
        { reportingMonth: 7, amount: 200 },
        { reportingMonth: 6, amount: 200 },
        { reportingMonth: 5, amount: 200 },
      ],
    },
    {
      lastName: 'Петришин',
      firstName: 'Ольга',
      membershipFees: [
        { reportingMonth: 10, amount: 200 },
        { reportingMonth: 9, amount: 200 },
        { reportingMonth: 8, amount: 200 },
        { reportingMonth: 6, amount: 200 },
        { reportingMonth: 5, amount: 200 },
        { reportingMonth: 4, amount: 200 },
        { reportingMonth: 3, amount: 200 },
        { reportingMonth: 2, amount: 200 },
      ],
    },
    {
      lastName: 'Созанська',
      firstName: 'Ірина',
      membershipFees: [
        { reportingMonth: 10, amount: 200 },
        { reportingMonth: 9, amount: 200 },
        { reportingMonth: 8, amount: 200 },
        { reportingMonth: 7, amount: 200 },
        { reportingMonth: 6, amount: 200 },
        { reportingMonth: 5, amount: 200 },
        { reportingMonth: 4, amount: 200 },
        { reportingMonth: 3, amount: 200 },
        { reportingMonth: 2, amount: 200 },
      ],
    },
    {
      lastName: 'Татаревич',
      firstName: 'Галина',
      membershipFees: [
        { reportingMonth: 11, amount: 200 },
        { reportingMonth: 10, amount: 200 },
        { reportingMonth: 9, amount: 200 },
        { reportingMonth: 8, amount: 200 },
        { reportingMonth: 7, amount: 200 },
        { reportingMonth: 6, amount: 200 },
      ],
    },
    {
      lastName: 'Франчук',
      firstName: 'Тетяна',
      membershipFees: [
        { reportingMonth: 10, amount: 200 },
        { reportingMonth: 9, amount: 200 },
        { reportingMonth: 8, amount: 200 },
        { reportingMonth: 7, amount: 200 },
        { reportingMonth: 6, amount: 200 },
        { reportingMonth: 4, amount: 200 },
        { reportingMonth: 2, amount: 200 },
      ],
    },
    {
      lastName: 'Чапля',
      firstName: 'Уляна',
      membershipFees: [
        { reportingMonth: 12, amount: 200 },
        { reportingMonth: 11, amount: 200 },
        { reportingMonth: 10, amount: 200 },
        { reportingMonth: 9, amount: 200 },
        { reportingMonth: 8, amount: 200 },
        { reportingMonth: 7, amount: 200 },
        { reportingMonth: 6, amount: 200 },
        { reportingMonth: 5, amount: 200 },
        { reportingMonth: 4, amount: 200 },
        { reportingMonth: 3, amount: 200 },
        { reportingMonth: 2, amount: 200 },
      ],
    },
    {
      lastName: 'Шатинська',
      firstName: 'Альона',
      membershipFees: [
        { reportingMonth: 10, amount: 200 },
        { reportingMonth: 9, amount: 200 },
        { reportingMonth: 8, amount: 200 },
        { reportingMonth: 7, amount: 200 },
        { reportingMonth: 6, amount: 200 },
        { reportingMonth: 5, amount: 200 },
        { reportingMonth: 4, amount: 200 },
        { reportingMonth: 3, amount: 200 },
        { reportingMonth: 2, amount: 200 },
      ],
    },
  ],
  expenses: [],
};
